# Generated by Django 4.0.3 on 2022-04-03 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'admin',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('issue', models.CharField(max_length=1000)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('skill', models.CharField(max_length=1000)),
                ('slogan', models.CharField(max_length=500)),
                ('votes', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'candidate',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('position', models.CharField(max_length=100)),
                ('minyear', models.IntegerField(db_column='minYear')),
                ('winneris', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'position',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Voters',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('stream', models.CharField(max_length=100)),
                ('regno', models.IntegerField(db_column='regNo', unique=True)),
                ('year', models.IntegerField()),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'voters',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Winner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ratio', models.IntegerField(blank=True, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='app.candidate')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='app.position')),
            ],
            options={
                'db_table': 'winner',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote', to='app.candidate')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote', to='app.position')),
                ('voters', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote', to='app.voters')),
            ],
            options={
                'db_table': 'vote',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='candidate',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate', to='app.position'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='voters',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate', to='app.voters'),
        ),
    ]
