# Generated by Django 4.0.3 on 2022-04-28 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_voters_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userid', models.IntegerField(unique=True)),
                ('img', models.TextField(blank=True, max_length=100000, null=True)),
            ],
            options={
                'db_table': 'image',
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='voters',
            name='image',
        ),
    ]
